+function(){var f;var l=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},m=function(a){if(l(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&l(a))return a;return null},n=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},r=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var t=["-ms-","-moz-","-webkit-",""],v=function(a,b,c,d){for(var e,h,g=0;g<t.length;++g)e=t[g]+b,h=(d?t[g]:"")+c,a.style.setProperty(e,h)};var w=function(a,b,c){var d;c?(d=document.createEvent("CustomEvent"),d.initCustomEvent(a,!0,!0,c)):(d=document.createEvent("Event"),d.initEvent(a,!0,!0));b.dispatchEvent(d);return d},x=function(a,b){setTimeout(function(){w("autoplayended",a,b)},0)},y=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var A=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var B=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},C=function(a,b){this.h=a;this.i=null;this.fa=b;this.B=!1};
C.prototype.play=function(a,b,c){if(this.h.frameCount&&null==this.i){b=b||"forwards";var d;c?(d=Math.floor(a/c),a=c):(d=this.h.frameCount,a/=d);var e=[],h=B(this.h);c=h;for(var g=0;g<d;g++){if(0<g||!this.fa)c=D(c+E(b,1),this.h.frameCount);e.push(c)}b=function(){if(e.length){var a=e.shift();this.B=!0;this.h.goToFrame(a+1);this.B=!1;F(this.h,"frameautoplayed",a+1)}else this.stop(!0),this.h.goToFrame(h+1)}.bind(this);this.i=setInterval(b,a);setTimeout(b)}};
C.prototype.stop=function(a){!this.B&&this.i&&(clearInterval(this.i),x(this.h,{completed:!!a}),this.i=null)};
var G=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},H=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(G(A(a[c])))}return b},I=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];"img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")&&(null!=b?e.setAttribute("scaling",b):e.removeAttribute("scaling"))}},F=function(a,b,c){w(b,a,{id:c||a.currentIndex})},J=function(a,b){var c=b.length;b=b.splice(0,
c);for(var d,e=0;e<c;e++)d=b[e],"frameshown"==d?F(a,d):w(d,a)},E=function(a,b){return"left"==a||"backwards"==a?-b:b},D=function(a,b){return(a%b+b)%b},K=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.pause()})},L=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.play()})};var M=function(a){var b;b=n(a,"frame-width",-1);-1==b&&(b=parseInt(.8*a.clientWidth,10));var c=a.hasAttribute("show-reflection"),d=n(a,"frame-height",-1);-1==d&&(d=c?parseInt(4*a.clientHeight/7,10):parseInt(6*a.clientHeight/7,10));var e=n(a,"neighbor-translation-x",-1);-1==e&&(e=parseInt(b/8,10));if(a.hasAttribute("neighbor-translation-x"))a:{var h=d,g;b:switch(a.getAttribute("clamp-frame-size-to-image")){case "true":g=!0;break b;case "false":g=!1;break b;default:g=!0}if(g){var k=a.hasAttribute("scaling")?
a.getAttribute("scaling"):"contain";if((g="contain"==k)||"none"==k){for(var k=-1,u=a.frameCount,z=0;z<u;z++){var p=a.getFrame(z+1);if("img"!=p.tagName.toLowerCase()||"gwd-image"!=p.getAttribute("is"))break a;var q=p,p=q.assetWidth,q=q.assetHeight;0<p&&0<q&&(k=Math.max(k,g?p/q<b/h?p/q*h:b:p))}b=-1!=k?Math.min(b,k):b}}}h=n(a,"neighbor-translation-y",-1);-1==h&&(h=parseInt(d/-10,10));g=n(a,"neighbor-translation-z",-1);-1==g&&(g=-d);a.f&&(d-=36);return{autoplay:a.hasAttribute("autoplay"),o:b,U:d,Y:n(a,
"neighbor-rotation-y",38),Z:e,K:h,$:g,transitionDuration:n(a,"transition-duration",600),ia:c,ga:n(a,"start-frame",2)}},N=function(a,b,c,d,e){b="translate3d("+b+"px, "+c+"px, "+d+"px)";e&&(b="rotate3d(0, 1, 0, "+e+"deg) "+b);v(a,"transform",b)},O=function(a,b){v(a,"transition","transform "+b+"ms",!0)};var P=function(a,b){function c(){}c.prototype=b.prototype;a.O=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ha=function(a,c,h){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var Q=function(){};P(Q,HTMLElement);f=Q.prototype;f.createdCallback=function(){this.frames=[];this.a=null;this.b=0;this.m=1;this.l=new C(this,!0);Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.V.bind(this)});Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.X.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.W.bind(this)});this.M=this.hasAttribute("pause-front-media");this.N=this.hasAttribute("resume-next-media")};
f.attributeChangedCallback=function(a){switch(a){case "pause-front-media":this.M=this.hasAttribute("pause-front-media");break;case "resume-next-media":this.N=this.hasAttribute("resume-next-media")}};f.getFrame=function(a){if(0!=this.b)return this.frames[a-1]};f.gwdLoad=function(){};f.gwdIsLoaded=function(){return!0};f.goToFrame=function(a,b){this.stopRotation();0!=this.b&&(a>this.b?a=this.b:1>a&&(a=1),this.I(a,b))};f.I=function(a){this.a=a-1};
var R=function(a,b,c,d){if(null!=a.a){var e=D(a.a+E(b,a.m||1),a.m*Math.ceil(a.b/a.m));null!=d&&!d&&("forwards"==b&&e<a.a||"backwards"==b&&e>a.a)||a.goToFrame(e+1,c||"slide")}};f=Q.prototype;f.goBackwards=function(a,b){return R(this,"backwards",a,b)};f.goForwards=function(a,b){return R(this,"forwards",a,b)};f.rotateOnce=function(a,b){this.l.play(a||0,b)};f.stopRotation=function(){this.l.stop()};f.V=function(){return 0<this.b?this.a+1:void 0};f.X=function(){return this.m};f.W=function(){return this.b};
var S=function(a,b){null!=a.a&&a.a!=b&&(a.M&&K(a.frames[a.a]),a.N&&L(a.frames[b]))};var T=function(){};P(T,Q);f=T.prototype;
f.createdCallback=function(){T.O.createdCallback.call(this);this.C=!1;this.g=null;this.J=-1;this.F=0;var a=document.createElement("gwd-gesture");a.className="gesture";this.A=a;this.T=this.da.bind(this);this.S=this.ea.bind(this);this.R=this.ca.bind(this);this.P=this.ba.bind(this);this.v=w.bind(null,"firstinteraction",this);this.L=this.aa.bind(this);this.G=!1;this.D=[];this.j=J.bind(null,this,this.D);this.u=[];this.H=0;if(this.w=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.c=
null;this.s=0;this.l=new C(this,!1);this.f=null};
f.attachedCallback=function(){var a=this.A;this.s=this.s||this.clientWidth/2;a.addEventListener("trackstart",this.T,!1);a.addEventListener("track",this.S,!1);a.addEventListener("trackend",this.R,!1);a.addEventListener("tap",this.P,!1);this.addEventListener("transitionend",this.j,!1);this.addEventListener("webkitTransitionEnd",this.j,!1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=m(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&
this.gwdLoad()}};f.detachedCallback=function(){var a=this.A;a.removeEventListener("trackstart",this.T,!1);a.removeEventListener("track",this.S,!1);a.removeEventListener("trackend",this.R,!1);a.removeEventListener("tap",this.P,!1);this.removeEventListener("transitionend",this.j);this.removeEventListener("webkitTransitionEnd",this.j)};f.I=function(a,b){b="none"!=b;var c=this.c.transitionDuration;S(this,a-1);U(this,b?c:0);V(this,a-1)};
f.rotateOnce=function(a,b){this.l.play(a||this.c.transitionDuration*this.b,b)};f.gwdIsLoaded=function(){return this.C};f.gwdLoad=function(){if(!this.C&&!this.g){var a;if(this.w)a=H(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;W(this)}};
var W=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.f=null;a.g&&a.g.removeEventListener("pageload",a.L,!1);for(var b=a.frames,c=document.createElement("div","gwd-page"),d,e=0;e<b.length;++e)d=b[e],v(d,"user-select","none"),d.classList.add("frame"),c.appendChild(d);y(c,c.gwdLoad.bind(c));a.g=c;c.className=a.hasAttribute("show-reflection")?"container reflection":"container";c.addEventListener("pageload",a.L,!1);I(a.frames,a.getAttribute("scaling"));a.appendChild(c);a.appendChild(a.A)};
T.prototype.aa=function(a){if(this.g===a.target){this.C=!0;this.b=this.frames.length;this.u=[];this.H=this.b;X(this);if(this.b){a=this.c.ga-1;if(0>a||a>=this.b)a=0;U(this,0);V(this,a);this.c.autoplay&&setTimeout(this.rotateOnce.bind(this),0)}Y(this);w("allframesloaded",this);w("ready",this)}};
T.prototype.attributeChangedCallback=function(a){T.O.attributeChangedCallback.call(this,a);switch(a){case "images":this.w=!0;this.b=0;this.a=null;this.frames=H(this.getAttribute(a));W(this);break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":Y(this);break;case "scaling":I(this.frames,this.getAttribute("scaling"));break;case "style":case "class":break;default:this.c=M(this)}};
var X=function(a){a.c=M(a);for(var b=0,c,d=0;d<a.frames.length;d++)c=a.frames[d],c.style.left=b+"px",c.style.width=a.c.o+"px",c.style.height=a.c.U+"px",b+=a.c.o};T.prototype.da=function(){null!=this.a&&(this.stopRotation(),this.F=this.a,U(this,0))};T.prototype.ea=function(a){if(this.b){this.v&&(this.v(),this.v=null);a=-a.dx/this.c.o;var b=Math.round(a);Z(this,this.F+b,a-b)}};
T.prototype.ca=function(){if(null!=this.a){U(this,this.c.transitionDuration);var a=this.a;V(this,a);this.F!=a&&(0==a?w("reachleftend",this):a==this.b-1&&w("reachrightend",this))}};T.prototype.ba=function(){this.b&&F(this,"frametap")};
var U=function(a,b){a.G=0<b;a.g&&O(a.g,b);for(var c=0;c<a.b;++c)O(a.frames[c],b)},V=function(a,b){a.frames[b]&&(a.a=b,Z(a,b,0,a.b),a.D.push("frameshown"),a.u[b]||(a.u[b]=!0,--a.H||a.D.push("allframesviewed")));a.G||a.j()},Z=function(a,b,c,d){for(var e=a.c,h,g=d||1,k=-g;k<=g;++k)if((d=a.frames[k+b])&&0<=c*k){0>k?h=1-Math.abs(c):0<k?h=Math.abs(c)-1:(S(a,b),a.a=b,h=c);var u=Math.abs(h);N(d,e.Z*h,e.K*u,e.$*u,e.Y*h)}a.J!=a.a&&null!=a.a&&(a.J=a.a,F(a,"frameactivated"));N(a.g,a.s-(b+c+.5)*e.o,-e.K,0)},Y=
function(a){var b=a.hasAttribute("has-navigation"),c=!!a.f;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.f=document.createElement("gwd-gallerynavigation"),a.f.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.f)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.f),a.f=null);a.f&&(r(a,"navigation-highlight",a.f,"highlight"),r(a,"navigation-thumbnails",a.f,"use-thumbnails"));X(a)};document.registerElement("gwd-carouselgallery",{prototype:T.prototype});}()
